### ISSUE TITLE
tronbox init windows error.

### ISSUE THREAD

**Issue by RyoungHo** [TRON-US/tronbox#22]
bash error.

```
tronbox init
Downloading...
Unpacking...
Setting up...
Error: Command failed: bash post-unpack.sh && rm post-unpack.sh && npm install
'bash'��(��) ���� �Ǵ� �ܺ� ����, ������ �� �ִ� ���α׷�, �Ǵ�
��ġ ������ �ƴմϴ�.

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
```

**Comment by sullof** [comment]
Sorry for responding so late. I think that this has been fixed later.
